name: deploy

on:
  - push

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31

      - run: |
          nix build
          cp -r result/* ./

      - name: upload
        uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: ./

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: deploy page
        id: deployment
        uses: actions/deploy-pages@v4
